# -*- coding: utf-8 -*-
"""Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Bb--MOAPShIPXqLw2e1bz7nBzayl2r8
"""

# Step 1: Simple recursive factorial (assumes n == 1 as base case)
def factorial_step1(n):
    # This version only handles n == 1 as base case and will fail for n == 0
    if n == 1:
        return 1
    return n * factorial_step1(n - 1)



# Final: Complete, documented program that:
# - validates input is an integer
# - rejects negative numbers
# - uses an iterative implementation (avoids recursion depth issues)
def factorial(n):
    """
    Compute factorial of a non-negative integer n.
    Raises:
      TypeError: if n is not an integer
      ValueError: if n is negative
    """
    if not isinstance(n, int):
        raise TypeError("Factorial is only defined for integers.")
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers.")
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result

# User input section
try:
    user_input = input("\nEnter a non-negative integer to compute its factorial: ")
    num = int(user_input)  # may raise ValueError if input is not an integer string
    print(f"Result: {num}! = {factorial(num)}")
except ValueError as ve:
    print("Error:", ve)
except TypeError as te:
    print("Error:", te)