# -*- coding: utf-8 -*-
"""Assignment 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2SqUnxd12MExJw5X346LmWiFWE9gs51

Student class
"""

class Student:
    """
    Simple Student class with attributes:
      - name (str)
      - roll_no (str/int)
      - age (int)
      - grades (dict) : optional, e.g. {'Math': 90, 'CS': 95}
    Provides:
      - display_details(): prints a formatted summary
      - average_grade(): returns float or None if no grades
    """
    def __init__(self, name: str, roll_no, age: int, grades: dict = None):
        if not isinstance(name, str) or name.strip() == "":
            raise ValueError("name must be a non-empty string")
        if not isinstance(age, int) or age < 0:
            raise ValueError("age must be a non-negative integer")
        self.name = name.strip()
        self.roll_no = roll_no
        self.age = age
        self.grades = dict(grades) if grades else {}

    def display_details(self):
        print(f"Student: {self.name}")
        print(f"Roll No: {self.roll_no}")
        print(f"Age: {self.age}")
        if self.grades:
            avg = self.average_grade()
            print("Grades:")
            for subj, score in self.grades.items():
                print(f"  {subj}: {score}")
            print(f"Average grade: {avg:.2f}")
        else:
            print("Grades: No grades available")

    def average_grade(self):
        if not self.grades:
            return None
        values = [v for v in self.grades.values() if isinstance(v, (int, float))]
        return sum(values) / len(values) if values else None

if __name__ == "__main__":
    s1 = Student("Alice Johnson", "CS21-001", 19, {"Math": 88, "AI": 92})
    s2 = Student("Bob Kumar", "CS21-002", 20)
    print("---- Student 1 ----")
    s1.display_details()
    print("\n---- Student 2 ----")
    s2.display_details()

"""Multiples using loops"""

def print_first_10_multiples(n: int):
    """
    Prints first 10 multiples of n using a for-loop (1..10).
    Raises ValueError if n is not an int or is 0 (0 is allowed but we handle it).
    """
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    print(f"First 10 multiples of {n} (for loop):")
    for i in range(1, 11):
        print(f"{n} x {i} = {n * i}")

def print_first_10_multiples_while(n: int):
    """
    Same output but implemented with a while loop.
    """
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    print(f"First 10 multiples of {n} (while loop):")
    i = 1
    while i <= 10:
        print(f"{n} x {i} = {n * i}")
        i += 1

def first_10_multiples_list(n: int):
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    return [n * i for i in range(1, 11)]
if __name__ == "__main__":
    print_first_10_multiples(5)
    print()  # spacing
    print_first_10_multiples_while(5)
    print()
    print("As list:", first_10_multiples_list(5))

"""Conditional Statements"""

def classify_age(age: int) -> str:
    """
    Classify age into groups using nested if-elif-else.
    Groups:
      - 'Infant' : 0-1
      - 'Toddler' : 2-3
      - 'Child' : 4-12
      - 'Teen' : 13-19
      - 'Young Adult' : 20-35
      - 'Adult' : 36-60
      - 'Senior' : 61+
    Raises ValueError for negative ages or non-integers.
    """
    if not isinstance(age, int):
        raise ValueError("age must be an integer")
    if age < 0:
        raise ValueError("age cannot be negative")

    # Top-level nested conditional structure:
    if age <= 1:
        return "Infant"
    else:
        if age <= 3:
            return "Toddler"
        else:
            if age <= 12:
                return "Child"
            elif age <= 19:
                return "Teen"
            else:
                if age <= 35:
                    return "Young Adult"
                else:
                    if age <= 60:
                        return "Adult"
                    else:
                        return "Senior"

if __name__ == "__main__":
    test_ages = [0, 1, 2, 5, 13, 25, 45, 75]
    for a in test_ages:
        group = classify_age(a)
        print(f"Age {a}: {group}")

"""For and While loops"""

def sum_to_n_for(n: int) -> int:
    """
    Calculate sum of first n natural numbers using a for-loop.
    If n < 0: raises ValueError.
    """
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    if n < 0:
        raise ValueError("n must be non-negative")
    total = 0
    for i in range(1, n + 1):
        total += i
    return total

def sum_to_n_while(n: int) -> int:
    """
    Calculate sum of first n natural numbers using a while loop.
    """
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    if n < 0:
        raise ValueError("n must be non-negative")
    total = 0
    i = 1
    while i <= n:
        total += i
        i += 1
    return total

def sum_to_n_formula(n: int) -> int:
    """
    Efficient formula-based calculation: n*(n+1)//2
    """
    if not isinstance(n, int):
        raise ValueError("n must be an integer")
    if n < 0:
        raise ValueError("n must be non-negative")
    return n * (n + 1) // 2

if __name__ == "__main__":
    for n in [0, 1, 5, 10, 100]:
        f = sum_to_n_for(n)
        w = sum_to_n_while(n)
        frm = sum_to_n_formula(n)
        assert f == w == frm, "Mismatch between methods!"
        print(f"n={n} => sum = {f} (verified across for/while/formula)")

"""BankAccount"""

# ✅ BankAccount Program with User Input (Google Colab READY)

class InsufficientFunds(Exception):
    """Raised when user tries to withdraw more than available balance."""
    pass

class BankAccount:
    def __init__(self, owner: str, balance: float = 0.0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount: float):
        if amount <= 0:
            print("❌ Deposit amount should be greater than 0.")
        else:
            self.balance += amount
            print(f"✅ Successfully deposited ₹{amount}. Updated balance: ₹{self.balance}")

    def withdraw(self, amount: float):
        if amount <= 0:
            print("❌ Withdrawal amount should be greater than 0.")
        elif amount > self.balance:
            raise InsufficientFunds("⚠️ Insufficient funds in the account.")
        else:
            self.balance -= amount
            print(f"✅ Successfully withdrawn ₹{amount}. Updated balance: ₹{self.balance}")

    def get_balance(self):
        return self.balance


# ------- User Input Interaction -------
print("\n====== 🏦 Bank Account Simulation 🏦 ======\n")

owner = input("Enter account holder name: ")
initial_balance = float(input("Enter initial balance: "))

account = BankAccount(owner, initial_balance)
print(f"\n✅ Account Created Successfully for {owner} with balance ₹{initial_balance}\n")

while True:
    print("\nChoose an option:")
    print("1. Deposit Money")
    print("2. Withdraw Money")
    print("3. Check Balance")
    print("4. Exit Program")

    choice = input("\nEnter your choice (1/2/3/4): ")

    if choice == "1":
        amount = float(input("Enter deposit amount: ₹"))
        account.deposit(amount)

    elif choice == "2":
        amount = float(input("Enter withdrawal amount: ₹"))
        try:
            account.withdraw(amount)
        except InsufficientFunds as e:
            print(e)

    elif choice == "3":
        print(f"💰 Current Balance: ₹{account.get_balance()}")

    elif choice == "4":
        print("\n✅ Thank you for using the Bank System. Goodbye!")
        break

    else:
        print("❌ Invalid option. Please try again.")