# -*- coding: utf-8 -*-
"""Assignment 7.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yD1gzBRdN2BQBgKitlc6colkXTASC7g
"""

numbers = [1, 2, 3]

index = 2

if index < len(numbers):
    print(numbers[index])
else:
    print(f"❌ Index {index} out of range. Max index is {len(numbers)-1}")

