# -*- coding: utf-8 -*-
"""Assignment 7.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yD1gzBRdN2BQBgKitlc6colkXTASC7g
"""

class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

s1 = Student("John", 21)
print("Name:", s1.name, "| Age:", s1.age)

