# -*- coding: utf-8 -*-
"""Assignment 7.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yD1gzBRdN2BQBgKitlc6colkXTASC7g
"""

def add(a, b):
    return a + b

# Test
print("Addition Result:", add(10, 5))