# -*- coding: utf-8 -*-
"""Assignment 7.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yD1gzBRdN2BQBgKitlc6colkXTASC7g
"""

def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("❌ Error: Division by Zero is not allowed.")
        return None

# Test
print("Result:", divide(10, 5))
print("Result:", divide(10, 2))