# -*- coding: utf-8 -*-
"""Assignment 7.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yD1gzBRdN2BQBgKitlc6colkXTASC7g
"""

i = 1
while i <= 5:
    print(i)
    i += 1